### ISSUE TITLE
MidiIn implementation Help

### ISSUE THREAD

**Issue by ableton4you** [waterjump/volca-share#45]
Hi, how can i make the MidiIn to work and turn the knobs on the corresponding midi channels with an external controller?

**Comment by waterjump** [comment]
Hi.  MIDI In was previously not supported but I've added it as of https://github.com/waterjump/volca-share/commit/91871b025afe60e71743a6bae3f2a144616029d9.  Give it a try and let me know what you think.

**Comment by waterjump** [comment]
Closing.  See previous comment.
